### ISSUE TITLE
Duplicate scrobbles

### ISSUE THREAD

**Issue by Nowena** [bgaesslein/mb_ScrobbleShortTracks#1]
Going to give you an example: His Hero Is Gone - T-Minus Zero

Song is 0:29.960 seconds. Perceived by Musicbee to be 30 seconds, therefore it scrobbles twice. Happens with any other songs which are 0:29.5 and above. Thus rounded up to 30 seconds.

**Comment by bgaesslein** [comment]
Thanks, I will look into it later today. Looks like I'll just have to round up the duration, should be an easy fix.

**Comment by Nowena** [comment]
Doesn't the 30 seconds rule stem from the fact spotify/deezer ads get scrobbled if they lift such restriction? Yet even more reasons to hate those leeches.

**Comment by bgaesslein** [comment]
I don't think there's any official statement as to why they do this.

**Comment by bgaesslein** [comment]
@Nowena try the latest release, please. This was driving me crazy, I couldn't replicate it at first. After _a lot_ of trial and error with audio generated in audacity I found out that the exact threshold seems to be 29.963ms. Anything above that will be scrobbled just fine with the built-in scrobbler. Hence, using the plugin would create a second scrobble for anything between that and the previously set value of 30 seconds.

**Comment by Nowena** [comment]
Uhhh... I still get duplicate scrobbles with the new version. Do you want my T-Minus Zero file to try it out?

Yea it is pretty insane. Scrobbling 30 second songs has been driving me crazy for 10 years. There's also no official Jason Statement on fake scrobblers and Taylor Swift/whatever pop spammers and k-poop bots bloating the entire site with their poop last stans fake playcounts to push that garbage and plaster it everywhere.

Then you go and outlaw the ability to submit 30 seconds and under grindcore/powerviolence/emoviolence songs for whatever reason. How can this be?

Nasum - I Hate People

**Comment by bgaesslein** [comment]
Yes, if you can send me the file somehow then I can troubleshoot some more. Really thought I had it there haha.

**Comment by Nowena** [comment]
Here it is, FLAC or die!

https://drive.proton.me/urls/QQGS9KW7CW#0UpWV8tt3XJf

**Comment by bgaesslein** [comment]
I tried it, it didn't scrobble twice for me. Very weird. I can't imagine that it somehow depends on the individual system but I don't know.
I wish musicBee was open source, it would be much easier to see what's going on. This way it's a complete stab in the dark. I can't know what the built-in scrobbler sents to the lfm API.

Some questions just to be sure:

Are you absolutely positive that it's scrobbling twice? Since I can only react to the event that notifies the plugin of a track change, the short tracks have to be scrobbled immediately, so it's possible that your last.fm page is already showing the scrobble but still the "Scrobbling now" thingy for the same track.

Are there any other plugins that might interfere somehow?

**Comment by Nowena** [comment]
Yea "scrobbling now" disappears then I get two scrobbles. I even delete the second one.

![you suffer but why](https://github.com/bgaesslein/mb_ScrobbleShortTracks/assets/52898460/738f375e-d085-4591-a224-2cf0e8818605)

I tried your plugin with a musicbee installation that was already modified on another laptop, still duplicated scrobbles. Subsequently tried a raw stock musicbee installation on yet another laptop. Still duplicated scrobbles.

The onyl way I do not get duplicated scrobbles is if I disable the built-in scrobbler. Perhaps that is why it is only submitted once for you.

**Comment by bgaesslein** [comment]
I was still using MusicBee 3.4 and just tried the latest 3.5 beta. Apparently something changed because I am now getting the double scrobble, too. Progress! I'll look into it further.

**Comment by bgaesslein** [comment]
After another round of extensive testing, it turns out MusicBee 3.5 changed the threshold for rounding up to 30 seconds to exactly 29,467ms because why not. :)
Try the latest v1.2.0 of the plugin, this should hopefully no longer scrobble twice. Keep the built-in plugin turned on so everything scrobbles correctly.

PS: I've only tried the latest beta. If there were any changes in between I'll probably not fix this because it's driving me crazy. :)
But I've added a config option to manually set an arbitrary threshold.

**Comment by Nowena** [comment]
It works. Finally. You did it. An unnamed Hero. You did what no one else felt like doing or could figure out. Even the very same Musicbee developer shrugged it off for years and said it was not possible.

The Unspeakable. Without trying to install stuff exclusive to linux or being confined to iTunes which I staunchly refused. A legend.

The custom threshold is a very nice touch, indeed. Now Hardcore music scrobblers shall find this simple plugin and scrobble away to spite last.fm and fight the fakeness.

The grindcore/powerviolence/emoviolence Gods can receive some appeasement at this moment. Some.

After so many years. They say hope dies last. I say being mad and angry, not accepting makes you Undead and eternal. When you descend into madness to fight insanities.

We can get back some sanity now. This is my N. Sanity Beach for the time being. Thank you.

**Comment by bgaesslein** [comment]
No problem. I mostly started looking into this because I wanted to listen to my "Short Music for Short People" compilation with 101 ~30 second songs and most of them wouldn't scrobble and I can't have that. Then I remembered that I'm a developer and there's probably something I can do about it.

Glad that I could help you, too.

**Comment by Nowena** [comment]
Oh, this will help a lot of random angry people about this for years. Lots of Hardcore scrobblers.

Check out Rat Music for Rat People Volumes I to III. 80s Hardcore. That is what the album you want to scrobble is parodying. The Tales of Terror songs Skate or Bate from the 2nd volume is specially epic. The lyrics and then the affected latter half that sounds like a drunken noisy metalpunk parody of some country hymn (most likely USA's which is what the song attacks and their war-loving culture). 

I can see clearly the Tales of Terror members drunkenly saluting the entire country. That random sole Square Cools (thrift shop Circle Jerks) song "I Don't Wanna Die for My Country".

CD Presents are rats, by the way. It fits. Where were you the last 10 years or when others that could achieve this refused to do it?

Doesn't matter. You are here now. "My name is Henry and you're locked in here with me now".

**Comment by Nowena** [comment]
You are a developer, yes. Do you know anything about CSS UI styles? There is something infuriating and insane I want to and must nuke from a web browser.

I have some code I got somewhere from random angry people on the internet saying it works for them, however, I do not know how to implement it.

I have the mighty need to turn that into a browser extension that any fed up user can install and gain back some of their sanity. We keep complaining about this and there were "experimental" features hidden in web browser "flags" pages somewhere to get rid of this Unspeakable thing but of course devs removed the code. 

This is actually mandatory. Essential. Quite a bit of things are minimum requirements which are not solved/corrected in order to just spite users/out of laziness/whatever. Just small details that actually drive you insane like these 30 second songs.

There were even existing extensions to solve this, however, they all mysteriously vanished from important extensions stores.

It's the infamous "tab audio indicator". I am sure you know to what I am referring, our scourge. One of many. If you do not know yourself, perhaps you can direct me to someone that can help. I wish I knew this stuff. Some things I figure out on my own. Some things are out of my control.

Either way, I do not accept. That is why insight/knowledge/help from others is very important.

**Comment by bgaesslein** [comment]
I'm afraid I can't help you there, no. I will look into the musical recommendations.
