### ISSUE TITLE
Only allow songs under 30 seconds to be scrobbled if at least 50% of it has been listened to

### ISSUE THREAD

**Issue by Rings4** [bgaesslein/mb_ScrobbleShortTracks#3]
Thank you very much for this plugin! I've wanted something like this for a very long time.

I just tested this with a 27-second song and found that skipping it at any point (even before 1 second has passed) scrobbles the song.

I know this might be very niche, but I think it'd be nice, if possible, for the plugin to only scrobble songs that have been listened to for at least 50% of the duration, like how the built-in normal last.fm scrobbler works. Hopefully that's something that can be done without much trouble!

**Comment by bgaesslein** [comment]
I actually already implemented this locally, will do a new release soon.

**Comment by bgaesslein** [comment]
Fixed in the latest release. Short songs will be scrobbled on completion now. I think 50% isn't possible because I don't think there's an event for that but this should suffice. At least skipping songs will also skip scrobbling them.
